services:

  db:
    hostname: ${POSTGRES_HOST:?err}
    image: postgres:18.1
    container_name: docuisine_postgres
    restart: no
    ports:
      - "${POSTGRES_PORT:?err}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/MAJOR/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
          "-h",
          "${POSTGRES_HOST}",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  db_data:
